#!/bin/sh

experiment=$1
experiment_ext=$1-ext

./collect.sh "$experiment"
./collect.sh "$experiment_ext"

mkdir "plots/$experiment"
./plot-by-pair $experiment training_acc
./plot-by-pair $experiment test_acc
./plot-by-pair $experiment test_loss
